Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/add'
  get 'messages/show'
  get 'messages/edit'
  root to: 'people#index'
  get 'people/find'
  post 'people/find'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people', to: 'people#index'
  get 'people/:id', to: 'people#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'
  post 'hello', to: 'hello#index'
  post 'hello/index'
end
